import React, { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { toast } from "sonner";
import { Database, Loader2, ShieldCheck, Eye, EyeOff } from "lucide-react";
import { format } from "date-fns";
import { ZipWriter, BlobWriter, TextReader } from "@zip.js/zip.js";

export const BackupExportButton: React.FC = () => {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [showPw, setShowPw] = useState(false);
  const [progress, setProgress] = useState<string>("");

  const reset = () => { setPassword(""); setConfirm(""); setProgress(""); };

  const run = async () => {
    if (password.length < 8) { toast.error("Password must be at least 8 characters"); return; }
    if (password !== confirm) { toast.error("Passwords do not match"); return; }
    setBusy(true);
    setProgress("Gathering data from server…");
    try {
      const { data, error } = await supabase.functions.invoke("backup-export", { body: {} });
      if (error) throw error;
      if (!data || data.error) throw new Error(data?.error ?? "Backup failed");

      setProgress("Building encrypted archive…");

      const stamp = format(new Date(), "yyyy-MM-dd-HHmm");
      const writer = new ZipWriter(new BlobWriter("application/zip"), {
        password,
        encryptionStrength: 3, // AES-256
      });

      // README
      const readme = `ShawScope Full Backup
Generated: ${data.generated_at}
Generated by: ${data.generated_by ?? "admin"}

This archive contains a JSON dump of every record stored in your ShawScope system at the moment of export.

Contents:
- manifest.json  Summary of tables and row counts
- data/<table>.json  One file per database table

To restore: the JSON files can be re-imported into the database by a developer.
Keep this file in a secure location. The archive is AES-256 encrypted with the password you chose.
`;
      await writer.add("README.txt", new TextReader(readme));

      const manifest: any = { generated_at: data.generated_at, generated_by: data.generated_by, tables: {} };
      for (const [name, payload] of Object.entries<any>(data.tables ?? {})) {
        manifest.tables[name] = { count: payload.count, error: payload.error ?? null };
        setProgress(`Packaging ${name} (${payload.count} rows)…`);
        await writer.add(`data/${name}.json`, new TextReader(JSON.stringify(payload.rows ?? [], null, 2)));
      }
      await writer.add("manifest.json", new TextReader(JSON.stringify(manifest, null, 2)));

      const blob = await writer.close();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `ShawScope-Backup-${stamp}.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);

      toast.success("Encrypted backup downloaded");
      setOpen(false);
      reset();
    } catch (e: any) {
      console.error(e);
      toast.error(e?.message ?? "Backup failed");
    }
    setBusy(false);
  };

  return (
    <>
      <Button
        onClick={() => setOpen(true)}
        className="bg-violet-500/15 border border-violet-500/40 text-violet-200 hover:bg-violet-500/25 h-9"
      >
        <Database className="h-4 w-4 mr-2" /> Download full encrypted backup
      </Button>

      <Dialog open={open} onOpenChange={(o) => { if (!busy) { setOpen(o); if (!o) reset(); } }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-violet-400" /> Encrypted ShawScope Backup</DialogTitle>
            <DialogDescription>
              Downloads a single password-protected ZIP containing every patient, appointment, policy,
              consent form, governance record, and message in your system. Choose a strong password —
              this cannot be recovered if lost.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3">
            <div className="space-y-1">
              <Label htmlFor="bk-pw">Password (min 8 characters)</Label>
              <div className="relative">
                <Input id="bk-pw" type={showPw ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} disabled={busy} autoComplete="new-password" />
                <button type="button" onClick={() => setShowPw(s => !s)} className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground">
                  {showPw ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>
            <div className="space-y-1">
              <Label htmlFor="bk-pw2">Confirm password</Label>
              <Input id="bk-pw2" type={showPw ? "text" : "password"} value={confirm} onChange={e => setConfirm(e.target.value)} disabled={busy} autoComplete="new-password" />
            </div>
            {progress && <p className="text-xs text-muted-foreground">{progress}</p>}
            <p className="text-[11px] text-muted-foreground">
              The archive uses AES-256 encryption. Open with any modern ZIP tool (Keka, 7-Zip, WinRAR, macOS Archive Utility).
              Save monthly as part of your governance routine.
            </p>
          </div>

          <DialogFooter>
            <Button variant="ghost" onClick={() => { setOpen(false); reset(); }} disabled={busy}>Cancel</Button>
            <Button onClick={run} disabled={busy || !password || !confirm} className="bg-violet-500/20 border border-violet-500/40 text-violet-100 hover:bg-violet-500/30">
              {busy ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Database className="h-4 w-4 mr-2" />}
              Generate &amp; download
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default BackupExportButton;